name: easy_prefs_gen
description: Code Generation for shared_preferences
version: 0.0.1
repository: https://github.com/mergehez/flutter_easy_prefs

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  analyzer: ^3.3.1
  build: ^2.2.1
  easy_prefs: ^0.0.1
  source_gen: ^1.2.1

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0

flutter: null
