name: easy_prefs_gen
description: Code Generation for shared_preferences with defining keys with their values. No need to write the type of the values.
version: 0.0.10
repository: https://github.com/mergehez/flutter_easy_prefs

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^5.13.0
  build: ^2.2.1
  easy_prefs: ^0.0.10
  source_gen: ^1.2.1

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^5.0.0

flutter: null
