name: easy_prefs_gen
description: Code Generation for shared_preferences
version: 0.0.2
repository: https://github.com/mergehez/flutter_easy_prefs

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.8.0
  build: ^2.2.1
  easy_prefs: ^0.0.2
  source_gen: ^1.2.1

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^5.0.0

flutter: null
