name: easy_prefs
description: easy-to-use shared_preferences with defining keys with their values. No need to write the type of the values.
version: 0.0.8
repository: https://github.com/mergehez/flutter_easy_prefs

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:

dev_dependencies:
  flutter_lints: ^5.0.0

flutter: