name: easy_prefs
description: easy-to-use shared_preferences
version: 0.0.1
repository: https://github.com/mergehez/flutter_easy_prefs

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:

dev_dependencies:
  flutter_lints: ^5.0.0

flutter: